spring.application.name=understand-spring-webflux-integrate-security-and-jwt
spring.main.banner-mode = off
spring.config.import=classpath:info/configs.properties
mongodb.ttknp.host=${MONGO.HOST}
mongodb.ttknp.database=${MONGO.DATABASE}
mongodb.ttknp.authenticationDatabase=admin
mongodb.ttknp.username=${MONGO.USERNAME}
mongodb.ttknp.password=${MONGO.PASSWORD}
mongodb.ttknp.port=${MONGO.PORT}


jwt.secret=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
jwt.expiration=3600000
jwt.password.encoder.secret=whatever_word
jwt.password.encoder.iteration=33
jwt.password.encoder.keyLength=256