spring.application.name=understand-spring-webflux-integrate-security
spring.main.banner-mode = off
spring.config.import=classpath:info/configs.properties

mongodb.ttknp.host=${MONGO_HOST}
mongodb.ttknp.database=${MONGO_DATABASE}
mongodb.ttknp.authenticationDatabase=admin
mongodb.ttknp.username=${MONGO_USERNAME}
mongodb.ttknp.password=${MONGO_PASSWORD}
mongodb.ttknp.port=${MONGO_PORT}


springbootwebfluxjjwt.jjwt.secret=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
springbootwebfluxjjwt.jjwt.expiration=28800
springbootwebfluxjjwt.password.encoder.secret=whatever_word
springbootwebfluxjjwt.password.encoder.iteration=33
springbootwebfluxjjwt.password.encoder.keyLength=256